<?php

namespace DoctrineORMModule\Proxy\__CG__\Financeiro\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ContaBancaria extends \Financeiro\Entity\ContaBancaria implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'id', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'criado_em', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'atualizado_em', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'agencia', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'conta', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'operacao', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'tipo', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'pessoa', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'documento', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'ativo', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'banco', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'usuario', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'clinica'];
        }

        return ['__isInitialized__', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'id', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'criado_em', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'atualizado_em', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'agencia', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'conta', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'operacao', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'tipo', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'pessoa', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'documento', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'ativo', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'banco', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'usuario', '' . "\0" . 'Financeiro\\Entity\\ContaBancaria' . "\0" . 'clinica'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ContaBancaria $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCriadoEm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCriadoEm', []);

        return parent::getCriadoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function setCriadoEm($criado_em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCriadoEm', [$criado_em]);

        return parent::setCriadoEm($criado_em);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtualizadoEm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtualizadoEm', []);

        return parent::getAtualizadoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtualizadoEm($atualizado_em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtualizadoEm', [$atualizado_em]);

        return parent::setAtualizadoEm($atualizado_em);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgencia', []);

        return parent::getAgencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgencia($agencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgencia', [$agencia]);

        return parent::setAgencia($agencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getConta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConta', []);

        return parent::getConta();
    }

    /**
     * {@inheritDoc}
     */
    public function setConta($conta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConta', [$conta]);

        return parent::setConta($conta);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperacao', []);

        return parent::getOperacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperacao($operacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperacao', [$operacao]);

        return parent::setOperacao($operacao);
    }

    /**
     * {@inheritDoc}
     */
    public function isTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTipo', []);

        return parent::isTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoStr', []);

        return parent::getTipoStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function isPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPessoa', []);

        return parent::isPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoa', []);

        return parent::getPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaStr', []);

        return parent::getPessoaStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoa($pessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoa', [$pessoa]);

        return parent::setPessoa($pessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumento', []);

        return parent::getDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumento($documento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumento', [$documento]);

        return parent::setDocumento($documento);
    }

    /**
     * {@inheritDoc}
     */
    public function isAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAtivo', []);

        return parent::isAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', []);

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivoStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivoStr', []);

        return parent::getAtivoStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', [$ativo]);

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanco', []);

        return parent::getBanco();
    }

    /**
     * {@inheritDoc}
     */
    public function setBanco($banco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanco', [$banco]);

        return parent::setBanco($banco);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getClinica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClinica', []);

        return parent::getClinica();
    }

    /**
     * {@inheritDoc}
     */
    public function setClinica($clinica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClinica', [$clinica]);

        return parent::setClinica($clinica);
    }

}
