<?php

namespace DoctrineORMModule\Proxy\__CG__\Financeiro\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Conta extends \Financeiro\Entity\Conta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'id', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'criado_em', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'atualizado_em', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'clinica', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'descricao', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'data', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'valor', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'desconto', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'tipo', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'categoria_conta', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'credor', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'devedor'];
        }

        return ['__isInitialized__', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'id', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'criado_em', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'atualizado_em', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'clinica', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'descricao', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'data', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'valor', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'desconto', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'tipo', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'categoria_conta', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'credor', '' . "\0" . 'Financeiro\\Entity\\Conta' . "\0" . 'devedor'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Conta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCriadoEm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCriadoEm', []);

        return parent::getCriadoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function setCriadoEm($criado_em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCriadoEm', [$criado_em]);

        return parent::setCriadoEm($criado_em);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtualizadoEm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtualizadoEm', []);

        return parent::getAtualizadoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtualizadoEm($atualizado_em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtualizadoEm', [$atualizado_em]);

        return parent::setAtualizadoEm($atualizado_em);
    }

    /**
     * {@inheritDoc}
     */
    public function getClinica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClinica', []);

        return parent::getClinica();
    }

    /**
     * {@inheritDoc}
     */
    public function setClinica($clinica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClinica', [$clinica]);

        return parent::setClinica($clinica);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', []);

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', [$descricao]);

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', []);

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function isTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTipo', []);

        return parent::isTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriaConta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriaConta', []);

        return parent::getCategoriaConta();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoriaConta($categoria_conta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoriaConta', [$categoria_conta]);

        return parent::setCategoriaConta($categoria_conta);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredor', []);

        return parent::getCredor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredor($credor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredor', [$credor]);

        return parent::setCredor($credor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevedor', []);

        return parent::getDevedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevedor($devedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevedor', [$devedor]);

        return parent::setDevedor($devedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValor', []);

        return parent::getValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setValor($valor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValor', [$valor]);

        return parent::setValor($valor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesconto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesconto', []);

        return parent::getDesconto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesconto($desconto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesconto', [$desconto]);

        return parent::setDesconto($desconto);
    }

}
